---
# roles/common/vars/main.yml

- name: Update package manager cache for Arch Linux
  become: yes
  package:
    update_cache: yes
  changed_when: False
  when: ansible_facts['os_family'] == 'Archlinux'
  tags:
    - packages

- name: Install general packages
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages.archlinux }}"
  when: ansible_facts['os_family'] == 'Archlinux'
  tags:
    - packages

- name: Install Thinkpad X1 Carbon Gen 8 specific packages
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages.thinkpad }}"
  when: ansible_facts['product_version'] == 'ThinkPad X1 Carbon Gen 8' and ansible_facts['os_family'] == 'Archlinux'
  tags:
    - packages

- name: Install python packages
  become: yes
  pip:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages.python }}"
  tags:
    - packages

- name: Ensure services are enabled
  become: yes
  service:
    name: "{{ item }}"
    enabled: yes
  loop: "{{ services.enabled }}"
  tags:
    - packages
    - services

# - name: Install dconf module dependencies
#   pip:
#     name: psutil
#     state: present
#   changed_when: false
#   tags:
#     - packages
#     - keyboard

# - name: Read currently available keyboard layouts in Gnome
#   become_user: daluca
#   dconf:
#     key: "/org/gnome/desktop/input-sources/sources"
#     state: read
#   register: keyboard_layouts
#   tags:
#     - keyboard

# - name: Print keyboard layouts
#   debug:
#     var: keyboard_layouts
#   tags:
#     - keyboard

# - name: Add dvorak to keyboard layout
#   become_user: daluca
#   dconf:
#     key: "/org/gnome/desktop/input-sources/sources"
#     # value: "[('xkb', 'us'), ('xkb', 'us+dvorak')]"
#     value: "[('xkb', 'us+dvorak'), ('xkb', 'us')]"
#     # value: "[('xkb', 'us')]"
#     # state: absent
#   tags:
#     - keyboard

# - name: Remove pip dependencies for dconf ansible module
#   pip:
#     name: psutil
#     state: absent
#   changed_when: false
#   tags:
#     - packages
#     - keyboard
    