---
# roles/common/vars/main.yml

packages:
  archlinux:
    - base
    - htop
    - firefox
    - pulseaudio
    - docker
    # - docker-compose
    - man-db
    - git
    - tmux
    - zsh
    - curl
    - rsync
    - nfs-utils
    - ntp
    - autofs
    - python-pip
    - ttf-droid
    - openvpn
    - networkmanager-openvpn
    - deluge
    - deluge-gtk
  aur:
    - ttf-ms-fonts
    - visual-studio-code-bin
    - exodus
    - zoom
    - g810-led-git
  thinkpad:
    - intel-ucode
    - sof-firmware
    - fwupd
    - gnome-firmware
    - linux-firmware
  python:
    - docker-compose

services:
  enabled:
    - docker
    - bluetooth
    - NetworkManager
    - ntpd
    - rpcbind
    - autofs
